### ISSUE TITLE
Only one arrow

### ISSUE THREAD

**Issue by entttom** [abin0992/AnimatedMapOverlay#1]
Hey!
Is it possible to show only 1 arrow starting at the beginning until it reaches the end and restart again?
i cant figure out how to do that!
do you have any ideas?

kind regards,
thomas

**Comment by abinrm** [comment]
Sorry for replying late.
Yes, this is possible. You can start one annotation from point A to Point B, you should keep checking if annotation.coordinate == coordinate of point B, then change annotation.coordinate to point A
